import Head from 'next/head'
import {Inter} from 'next/font/google'
import Nav from '../../components/navbar'
import FooterSimple from '../../components/footer'
import React from "react";
import {useAuthState} from 'react-firebase-hooks/auth'
import {auth} from '../../firebase/firebase'
import '../../firebase/firebase'
import SignInPage from "../../components/sign_in";

const inter = Inter({subsets: ['latin']})
export default function Home() {
    const [user] = useAuthState(auth)
    console.log(user)
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Nav/>
            <SignInPage/>
            <footer>
                <FooterSimple/>
            </footer>
        </>
    )
}
