import Head from 'next/head'
import {Inter} from 'next/font/google'
import Nav from '../../../components/navbar'
import FooterSimple from '../../../components/footer'
import React from "react";
import SignupForm from "../../../components/sign_up";

const inter = Inter({subsets: ['latin']})
export default function Podcast() {
    return (
        <>
            <Head>
                <title>Podcast</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Nav/>
            <SignupForm/>
            <footer>
                <FooterSimple/>
            </footer>
        </>
    )
}