import {Box, Flex, Grid, GridItem, Img, useColorModeValue} from "@chakra-ui/react";
import React from "react";

const HomePage2 = () => {
    return (
        <>
            <Box
                bg={useColorModeValue('gray.50', 'gray.800')}
                justifyContent='center'
                alignItems='center'
                marginLeft='-400px'
                marginRight='-400px'
            >
                <Grid
                    h='1000px'
                    templateRows='repeat(2, 1fr)'
                    templateColumns='repeat(5, 1fr)'
                    gap={16}
                >
                    <GridItem
                        colSpan={1}
                        rowSpan={2}
                        colStart={1}
                        colEnd={1}>
                        <Flex>
                        <Img
                            src="/defaultImage.svg"
                            alt="Logo"
                            width={300}
                            height={300}
                            borderRadius={8}
                            marginTop={0}
                            marginRight={8}
                            marginBottom={8}
                            marginLeft={8}
                            shadow={"2xl"}
                            border='1px'
                            borderColor='gray.400'
                        />
                    </Flex>
                        <Flex>
                        <Img
                            src="/defaultImage.svg"
                            alt="Logo"
                            width={300}
                            height={300}
                            borderRadius={8}
                            marginTop={0}
                            marginRight={8}
                            marginBottom={8}
                            marginLeft={8}
                            shadow={"2xl"}
                            border='1px'
                            borderColor='gray.400'
                        />
                    </Flex>
                    </GridItem>
                    <GridItem
                        colSpan={1}
                        rowSpan={2}
                        colStart={2}
                        colEnd={2}>
                        <Flex>
                            <Img
                                src="/defaultImage.svg"
                                alt="Logo"
                                width={300}
                                height={300}
                                borderRadius={8}
                                marginTop={0}
                                marginRight={8}
                                marginBottom={8}
                                marginLeft={8}
                                shadow={"2xl"}
                                border='1px'
                                borderColor='gray.400'
                            />
                        </Flex>
                        <Flex>
                            <Img
                                src="/defaultImage.svg"
                                alt="Logo"
                                width={300}
                                height={300}
                                borderRadius={8}
                                marginTop={0}
                                marginRight={8}
                                marginBottom={8}
                                marginLeft={8}
                                shadow={"2xl"}
                                border='1px'
                                borderColor='gray.400'
                            />
                        </Flex>
                    </GridItem>
                    <GridItem
                        rowSpan={2}
                        colSpan={1}
                        colStart={3}
                        colEnd={3}>
                        <Flex>
                        <Img
                            src="/hero_iphone.png"
                            alt="Logo"
                            width={650}
                            borderRadius={8}
                            marginTop={16}
                            marginRight={8}
                            marginBottom={8}
                            marginLeft={8}
                        />
                        </Flex>
                    </GridItem>
                    <GridItem
                        colSpan={1}
                        rowSpan={2}
                        colStart={4}
                        colEnd={4}>
                        <Flex>
                        <Img
                            src="/defaultImage.svg"
                            alt="Logo"
                            width={300}
                            height={300}
                            borderRadius={8}
                            marginTop={0}
                            marginRight={8}
                            marginBottom={8}
                            marginLeft={-36}
                            shadow={"2xl"}
                            border='1px'
                            borderColor='gray.400'
                        />
                        </Flex>
                        <Flex>
                        <Img
                            src="/defaultImage.svg"
                            alt="Logo"
                            width={300}
                            height={300}
                            borderRadius={8}
                            marginTop={0}
                            marginRight={8}
                            marginBottom={8}
                            marginLeft={-36}
                            shadow={"2xl"}
                            border='1px'
                            borderColor='gray.400'
                        />
                        </Flex>

                    </GridItem>
                    <GridItem
                        colSpan={1}
                        rowSpan={2}
                        colStart={5}
                        colEnd={5}>
                        <Flex>
                            <Img
                                src="/defaultImage.svg"
                                alt="Logo"
                                width={300}
                                height={300}
                                borderRadius={8}
                                marginTop={0}
                                marginRight={8}
                                marginBottom={8}
                                marginLeft={8}
                                shadow={"2xl"}
                                border='1px'
                                borderColor='gray.400'
                            />
                        </Flex>
                        <Flex>
                            <Img
                                src="/defaultImage.svg"
                                alt="Logo"
                                width={300}
                                height={300}
                                borderRadius={8}
                                marginTop={0}
                                marginRight={8}
                                marginBottom={8}
                                marginLeft={8}
                                shadow={"2xl"}
                                border='1px'
                                borderColor='gray.400'
                            />
                        </Flex>

                    </GridItem>
                </Grid>
            </Box>
        </>
    )
}

export default HomePage2;