import {
  Flex,
  Box,
  Stack,
  Link,
  Button,
  Heading,
  Text,
  useColorModeValue,
  FormControl,
  FormLabel,
  Input,
} from "@chakra-ui/react";
import { signIn } from "next-auth/react";
import Head from "next/head";
import React from "react";
import { FaGoogle } from "react-icons/fa";
import styles from "@/styles/Home.module.css";
import Image from "next/image";

export default function SignInPage({ providers }: any) {
  return (
    <>
      <Head>
        <title>Podcast</title>
        <meta
          name="página de podcast para profesionales del sector TIC"
          content="Generated by create next app"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        minH={"100vh"}
        align={"center"}
        justify={"center"}
        bg={useColorModeValue("gray.50", "gray.800")}
      >
        <Stack spacing={8} mx={"auto"} maxW={"lg"} py={12} px={6}>
          <Stack align={"center"}>
            <Heading fontSize={"4xl"}>Aquí letras degradadas</Heading>
            <Text fontSize={"lg"} color={"gray.600"}>
              to enjoy all of our cool{" "}
              <Link color={"purple.600"}>features</Link> ✌️
            </Text>
          </Stack>
          <Box
            rounded={"lg"}
            bg={useColorModeValue("white", "gray.700")}
            boxShadow={"lg"}
            p={8}
          >
            <Stack as={"form"} spacing={4}>
              <FormControl isRequired>
                <FormLabel>Email address</FormLabel>
                <Input type={"email"} id={"email"} />
              </FormControl>
              <FormControl isRequired>
                <FormLabel>Password</FormLabel>
                <Input type={"password"} id={"password"} />
              </FormControl>
              <Image
                className={styles.logo}
                src="/you-pod-nav.svg"
                alt="You-Pod Logo"
                width={100}
                height={100}
                priority
              />

              {Object.values(providers.providers).map((provider: any) => {
                return (
                  <Button
                    key={provider.id}
                    bg={"gray"}
                    color={"white"}
                    leftIcon={<FaGoogle />}
                    onClick={() => signIn(provider.id)}
                  >
                    Sign in with {provider.name}
                  </Button>
                );
              })}
            </Stack>
          </Box>
        </Stack>
      </Flex>
    </>
  );
}
