import Head from 'next/head'
import Image from 'next/image'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Nav from '../../../components/navbar'
import SmallWithNavigation from '../../../components/footer'
import React from "react";
import SimpleCard from "../../../components/sign_in";
import { getAuth, createUserWithEmailAndPassword } from "firebase/auth";

const inter = Inter({subsets: ['latin']})
export default function Podcast() {
    return (
        <>
            <Head>
                <title>Podcast</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Nav/>
            <SimpleCard/>
            <footer>
                <SmallWithNavigation/>
            </footer>
        </>
    )
}