import Head from 'next/head'
import {Inter} from 'next/font/google'
import Nav from '../../../components/navbar'
import SmallWithNavigation from '../../../components/footer'
import React from "react";
import {MyPlayer} from "../../../components/my_player";
import {Box} from "@chakra-ui/react";

import { useEffect, useState } from "react";
import { collection, getDocs } from "firebase/firestore";
import { db } from "../../../firebase/firebase";

const inter = Inter({subsets: ['latin']})
// export default function Podcast() {
export default function Podcast() {
    interface PodcastData {
        url: string;
        description: string;
        title: string;
    }

    const [podcastCollection, setPodcastCollection] = useState<PodcastData[]>([]);

    useEffect(() => {
        const fetchData = async () => {
            const dataCollection = collection(db, "podcast");
            const dataSnapshot = await getDocs(dataCollection);
            const podcastData = dataSnapshot.docs.map((doc) => doc.data() as PodcastData);
            setPodcastCollection(podcastData);
        };
        fetchData().then(r => {});
    }, []);

    return (
        <>
            <Head>
                <title>Podcast</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Nav/>
            <Box
                minH={'100vh'}>
                {podcastCollection.map((podcast) => {
                    return (
                        <MyPlayer key={podcast.title.toString()}
                                  url={podcast.url}
                                  title={podcast.title}
                                  description={podcast.description}
                        />
                    )
                })}
            </Box>
            <footer>
                <SmallWithNavigation/>
            </footer>
        </>
    )
}