import Head from 'next/head'
import Nav from '../../components/navbar'
import FooterSimple from '../../components/footer'
import React from "react";
import NewsletterForm from "../../components/newsletter_suscribe";
import {getSession, useSession} from "next-auth/react";

export default function Newsletter() {
    const {data: session, status} = useSession()
    if (status === 'authenticated') {
        return (
            <>
                <Head>
                    <title>Podcast</title>
                    <meta name="description" content="Generated by create next app"/>
                    <meta name="viewport" content="width=device-width, initial-scale=1"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>
                <Nav/>
                <NewsletterForm/>
                <footer>
                    <FooterSimple/>
                </footer>
            </>
        )
    }
}

export const getServerSideProps = async (context: any) => {
    const session = await getSession(context)
    if (!session) {
        return (
            {
                redirect: {
                    destination: '/'
                }
            }
        )
    }
    return {
        props: {session},
    }
}